### ISSUE TITLE
mmt needed at runtime (get rid of mmt-gensym)

### ISSUE THREAD

**Issue by darkfeline** [mrkkrp/mmt#2]
For Emacs packages providing macros, it is common to use `(eval-when-compile (require 'cl-lib))` so that the macros are expanded at compile time and the package would then not be needed at runtime.  `cl-lib` is an example of this.

However, it's impossible to do this with mmt because it uses the function `mmt-gensym` internally.  Therefore I must require mmt at runtime for my macro packages. This is also "infectious" in that it makes users of my macros require my package at runtime too.

Consider someone using a package that uses a package that uses another package:  foo -> bar -> baz.  Ordinarily if the macros get expanded at compile time, I don't even need bar or baz installed when I'm using foo.  However if I use mmt, now all of a sudden I need to load bar, baz, and mmt at runtime, potentially loading thousands of lines of useless code.

This can be solved simply by getting rid of the `mmt-gensym` alias, which is completely redundant as `cl-gensym` ships with Emacs.

**Comment by mrkkrp** [comment]
Do you want to prepare a PR?

**Comment by mrkkrp** [comment]
Resolved via #3.
